-- =====================================================
-- V17 Migration - Creates password_reset_token table
-- Required for password reset functionality
-- =====================================================

CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP(6) NOT NULL,
    user_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

-- Index for faster token lookups
CREATE INDEX idx_password_reset_token ON password_reset_token(token);
