-- V1 SQL MIGRATION
CREATE TABLE IF NOT EXISTS pomodoro_session
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_title    VARCHAR(255)                            NOT NULL,
    session_type     VARCHAR(255)                            NOT NULL,
    status           VARCHAR(255),
    focus_duration   BIGINT                                  NOT NULL,
    break_duration   BIGINT                                  NOT NULL,
    total_cycles     INTEGER,
    current_phase    VARCHAR(255),
    notes            TEXT,
    activity_id      BIGINT,
    started_at       TIMESTAMP WITHOUT TIME ZONE,
    completed_at     TIMESTAMP WITHOUT TIME ZONE,
    cycles_completed INTEGER                                 NOT NULL,
    is_deleted       BOOLEAN                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pomodoro_session PRIMARY KEY (id)
);

-- Add foreign key constraint only if activity table exists and constraint doesn't exist
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'activity') THEN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE constraint_schema = 'public' 
            AND constraint_name = 'fk_pomodoro_session_on_activity'
            AND table_name = 'pomodoro_session'
        ) THEN
            ALTER TABLE pomodoro_session
                ADD CONSTRAINT FK_POMODORO_SESSION_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id);
        END IF;
    END IF;
END $$;

-- Drop tables and sequences only if they exist
DROP TABLE IF EXISTS session_note CASCADE;
DROP SEQUENCE IF EXISTS pomodoro_session_id_seq CASCADE;