-- V1 SQL MIGRATION
CREATE TABLE pomodoro_session
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    session_title    VARCHAR(255)                            NOT NULL,
    session_type     VARCHAR(255)                            NOT NULL,
    status           VARCHAR(255),
    focus_duration   BIGINT                                  NOT NULL,
    break_duration   BIGINT                                  NOT NULL,
    total_cycles     INTEGER,
    current_phase    VARCHAR(255),
    notes            TEXT,
    activity_id      BIGINT,
    started_at       TIMESTAMP WITHOUT TIME ZONE,
    completed_at     TIMESTAMP WITHOUT TIME ZONE,
    cycles_completed INTEGER                                 NOT NULL,
    is_deleted       BOOLEAN                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pomodoro_session PRIMARY KEY (id)
);

ALTER TABLE pomodoro_session
    ADD CONSTRAINT FK_POMODORO_SESSION_ON_ACTIVITY FOREIGN KEY (activity_id) REFERENCES activity (id);

DROP TABLE session_note CASCADE;

DROP SEQUENCE pomodoro_session_id_seq CASCADE;