-- V1__.sql
-- Initial database schema for Pomodify application
-- Creates core tables: app_user, activity, user_push_token, refresh_token

-- Create app_user table
CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

-- Create activity table
CREATE TABLE IF NOT EXISTS activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    activity_name VARCHAR(255) NOT NULL,
    color VARCHAR(7),
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_activity PRIMARY KEY (id),
    CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

-- Create user_push_token table
CREATE TABLE IF NOT EXISTS user_push_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    token VARCHAR(500) NOT NULL,
    device_type VARCHAR(50),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_push_token PRIMARY KEY (id),
    CONSTRAINT fk_user_push_token_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT unique_user_token UNIQUE (user_id, token)
);

-- Create refresh_token table
CREATE TABLE IF NOT EXISTS refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    token VARCHAR(500) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

-- Create session_note table (will be deprecated in V9)
CREATE TABLE IF NOT EXISTS session_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT NOT NULL,
    activity_id BIGINT,
    note_text TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_session_note PRIMARY KEY (id),
    CONSTRAINT fk_session_note_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_session_note_activity FOREIGN KEY (activity_id) REFERENCES activity(id) ON DELETE SET NULL
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_app_user_email ON app_user(email);
CREATE INDEX IF NOT EXISTS idx_activity_user_id ON activity(user_id);
CREATE INDEX IF NOT EXISTS idx_activity_is_archived ON activity(is_archived);
CREATE INDEX IF NOT EXISTS idx_user_push_token_user_id ON user_push_token(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id ON refresh_token(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_expires_at ON refresh_token(expires_at);
CREATE INDEX IF NOT EXISTS idx_session_note_user_id ON session_note(user_id);
CREATE INDEX IF NOT EXISTS idx_session_note_activity_id ON session_note(activity_id);

-- Add table comments
COMMENT ON TABLE app_user IS 'Application users with authentication credentials';
COMMENT ON TABLE activity IS 'User-defined activities for time tracking';
COMMENT ON TABLE user_push_token IS 'FCM push notification tokens for mobile devices';
COMMENT ON TABLE refresh_token IS 'JWT refresh tokens for authentication';
COMMENT ON TABLE session_note IS 'Session notes (deprecated, replaced by pomodoro_session in V9)';