POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "daniel@example.com",
  "password": "Password@123"
}

###

POST {{base_url}}/activities
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Mobile App Development 3",
  "description": "Developing a mobile application for e-commerce",
  "categoryId": 1
}

###

GET {{base_url}}/activities/deleted
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{base_url}}/activities?page=0&size=10&sortBy=title&sortOrder=asc&categoryId=4
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

GET {{base_url}}/activities/16
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

PUT {{base_url}}/activities/14
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "newActivityTitle": "Updated Activity Title",
  "newActivityDescription": "Updated description",
  "newCategoryId": 2
}

###

DELETE {{base_url}}/activities/14
Authorization: Bearer {{accessToken}}
Content-Type: application/json
