### Register
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "firstName": "Daniel",
  "lastName": "Victorioso",
  "email": "daniel@example.com",
  "password": "Password@123"
}

### Login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "daniel@example.com",
  "password": "Password@123"
}

### Refresh Tokens
POST {{base_url}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

### Logout
POST {{base_url}}/auth/logout
Authorization: Bearer {{access_token}}

### Current User
GET {{base_url}}/auth/me
Authorization: Bearer {{access_token}}

### Get All Categories
GET {{base_url}}/category/all
Authorization: Bearer {{access_token}}

### Get All Deleted Categories
GET {{base_url}}/category/all-deleted
Authorization: Bearer {{access_token}}

### Create Category
POST {{base_url}}/categories
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "categoryName": "WebDev"
}

### Update Category
PUT {{base_url}}/category/3
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "newCategoryName": "Updated Work 4"
}

### Delete Category
DELETE {{base_url}}/category/3
Authorization: Bearer {{access_token}}
