POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "daniel@example.com",
  "password": "Password@123"
}

###
POST {{base_url}}/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "categoryName" : "Freelance"
}

###

GET {{base_url}}/categories
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###

PUT {{base_url}}/categories/5
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "newCategoryName" : "Updated Category Name"
}

###
DELETE {{base_url}}/categories/5
Authorization: Bearer {{accessToken}}
Content-Type: application/json
